POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "tourguide@gmail.com",
    "password": "abcd1234"
}
###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "tourguide@gmail.com",
    "password": "abcd1234"
}