POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jacob@example.com",
    "password": "supersecretpassword"
}
###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "phil@example.com",
    "password": "supersecretpassword"
}