GET http://localhost:3000/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTMwMTU0NTAzfQ.pycu_-UHwwCtLHUMFWytkcAYB5sVYIFjXJ6QKKQIG58

###
GET https://bookings-api-jsiopfmjry.now.sh/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTMwMTU0NTAzfQ.pycu_-UHwwCtLHUMFWytkcAYB5sVYIFjXJ6QKKQIG58


###
GET http://localhost:3000/bookings
